### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by tilahun12** [CityU-AIM-Group/NLTE#3]
![Screenshot 2022-07-12 081929](https://user-images.githubusercontent.com/50729468/178414624-51b905c1-6b85-4f16-99f8-75e59cee8294.png)

**Comment by xinyuliu-jeffrey** [comment]
This error is due to pytorch version incompatible. you have to change '1-' to '~' for some pytorch versions.

**Comment by tilahun12** [comment]
the error is on line 114 so how we can change it to ~ operator
![line](https://user-images.githubusercontent.com/50729468/178421084-1a3a52de-de7d-45e5-b222-38d267972b55.png)

**Comment by xinyuliu-jeffrey** [comment]
It seems to be occurring on line 80 according to the screenshot of the error
![image](https://user-images.githubusercontent.com/59467295/178421433-1169b483-87be-4005-84fd-a243735dfd9f.png)

**Comment by tilahun12** [comment]
on the first error it was on this line https://github.com/CityU-AIM-Group/NLTE/blob/a111390bcc38bd0c759a3a9d971a7d9defce88fb/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L80 so i change it according to your recommendation but it happen again on this line.https://github.com/CityU-AIM-Group/NLTE/blob/a111390bcc38bd0c759a3a9d971a7d9defce88fb/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L114

**Comment by tilahun12** [comment]
I am using pytorch version 1.4 with cuda 9.2

**Comment by xinyuliu-jeffrey** [comment]
You may try to install the following versions:

torch              1.1.0
torchvision        0.2.1

**Comment by tilahun12** [comment]
Ok but what about the python, cuda and gcc versions am still encountering version conflicts

**Comment by xinyuliu-jeffrey** [comment]
python 3.7.7, cuda 10.2, gcc 5.2.0. Actually i don't think this error is caused by version conflicts of python cuda or gcc. As in https://forum.opennmt.net/t/runtimeerror-subtraction-the-operator-with-a-bool-tensor-is-not-supported-if-you-are-trying-to-invert-a-mask-use-the-or-bitwise-not-operator-instead/2994/2, someone downgrade the pytorch from 1.2.0 to 1.1.0 and solved the problem.

**Comment by tilahun12** [comment]
tried downgrading the pytorch with but unable to rebuild torchvision again with python 3.7 and cuda 9.2
![gcc](https://user-images.githubusercontent.com/50729468/178434725-6a636fbe-67fe-41ed-92b2-64881a465068.png)

**Comment by xinyuliu-jeffrey** [comment]
torchvision version is not that important. make sure you have torch==1.1.0 in pip list is ok
