### ISSUE TITLE
The code does not contain an implementation of Potential Instance Mining

### ISSUE THREAD

**Issue by Jianyong-Zhao** [CityU-AIM-Group/NLTE#4]
hello，i read the code about RPN folders。
i find it is the same as https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch repository‘s code.
**so,i want to konw where is implementation of Potential Instance Mining**
Thanks

**Comment by xinyuliu-jeffrey** [comment]
Please find it here

https://github.com/CityU-AIM-Group/NLTE/blob/a111390bcc38bd0c759a3a9d971a7d9defce88fb/maskrcnn_benchmark/modeling/roi_heads/box_head/loss.py#L106

**Comment by Jianyong-Zhao** [comment]
Thnaks for your help.
Good night and sweet dreams
