### ISSUE TITLE
NLTE using YOLOV5

### ISSUE THREAD

**Issue by nanfei666** [CityU-AIM-Group/NLTE#5]
nice work, is it possible to use NLTE with YOLOV5 as the detector?

**Comment by xinyuliu-jeffrey** [comment]
@nanfei666 Thanks for your interest! Different from Faster R-CNN which is a two-stage detector, YOLOV5 is a single-stage detector that does not contain the region-proposal network (RPN). Therefore, NLTE does not support YOLOV5 currently.
